#!/bin/sh
ALL=$(awk 'END{printf "%d\n",NR}' core/*.ml)
CODE=$(ls -1 core/*.ml | grep -v Test.ml | xargs awk 'END{printf "%d\n",NR}')

echo "YVALUE=$ALL" >> $WORKSPACE/all_loc.properties
echo "YVALUE=$CODE" >> $WORKSPACE/code_loc.properties


