#!/bin/sh
ALL=$(awk '{ i += 1 } END{printf "%d\n",i}' core/*.ml msgpack/*.v)
CODE=$(ls -1 core/*.ml msgpack/*.v | grep -v Test.ml | xargs awk '{ i += 1 } END{printf "%d\n",i}')

echo "YVALUE=$ALL" >> $WORKSPACE/all_loc.properties
echo "YVALUE=$CODE" >> $WORKSPACE/code_loc.properties


