#!/bin/sh
ALL=$(awk '{ i += 1 } END{printf "%d\n",i}' core/*.ml)
CODE=$(ls -1 core/*.ml | grep -v Test.ml | xargs awk '{ i += 1 } END{printf "%d\n",i}')

echo "YVALUE=$ALL" >> $WORKSPACE/all_loc.properties


