--- !ditz.rubyforge.org,2008-03-06/project 
name: dominion
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: dominion
- !ditz.rubyforge.org,2008-03-06/component 
  name: protocol
releases: []

